# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'WEAyBPnlC.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QLabel, QLineEdit,
    QPushButton, QSizePolicy, QTabWidget, QVBoxLayout,
    QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(981, 606)
        palette = QPalette()
        brush = QBrush(QColor(164, 194, 201, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(27, 38, 41, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        brush2 = QBrush(QColor(0, 0, 0, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        brush3 = QBrush(QColor(120, 120, 120, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        Dialog.setPalette(palette)
        icon = QIcon()
        icon.addFile(u"../../../Downloads/cbd429e4aeb207be5ca385877731f117.ico", QSize(), QIcon.Normal, QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet(u"background-color: rgb(27, 38, 41);\n"
"border-left-color: rgb(164, 194, 201);\n"
"border-bottom-color: rgb(164, 194, 201);\n"
"border-right-color: rgb(164, 194, 201);\n"
"border-top-color: rgb(164, 194, 201);")
        self.tabWidget = QTabWidget(Dialog)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(20, 130, 941, 461))
        font = QFont()
        font.setFamilies([u"SDK_JP_Web"])
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet(u"background-color: rgb(39, 70, 84);\n"
"selection-color: rgb(99, 117, 117);\n"
"")
        self.tabWidget.setTabsClosable(False)
        self.tab_suma = QWidget()
        self.tab_suma.setObjectName(u"tab_suma")
        self.label_2 = QLabel(self.tab_suma)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 50, 221, 31))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush4 = QBrush(QColor(39, 70, 84, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush4)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush4)
        brush5 = QBrush(QColor(99, 117, 117, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.HighlightedText, brush5)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush5)
        self.label_2.setPalette(palette1)
        self.label_2.setStyleSheet(u"font: 16pt \"SDK_JP_Web\";\n"
"\n"
"")
        self.txt_sa00 = QLineEdit(self.tab_suma)
        self.txt_sa00.setObjectName(u"txt_sa00")
        self.txt_sa00.setGeometry(QRect(30, 110, 61, 61))
        font1 = QFont()
        font1.setFamilies([u"SDK_JP_Web"])
        font1.setPointSize(16)
        self.txt_sa00.setFont(font1)
        self.txt_sa00.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_sa00.setAlignment(Qt.AlignCenter)
        self.txt_sa10 = QLineEdit(self.tab_suma)
        self.txt_sa10.setObjectName(u"txt_sa10")
        self.txt_sa10.setGeometry(QRect(30, 190, 61, 61))
        self.txt_sa10.setFont(font1)
        self.txt_sa10.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_sa10.setAlignment(Qt.AlignCenter)
        self.txt_sa20 = QLineEdit(self.tab_suma)
        self.txt_sa20.setObjectName(u"txt_sa20")
        self.txt_sa20.setGeometry(QRect(30, 270, 61, 61))
        self.txt_sa20.setFont(font1)
        self.txt_sa20.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_sa20.setAlignment(Qt.AlignCenter)
        self.txt_sa01 = QLineEdit(self.tab_suma)
        self.txt_sa01.setObjectName(u"txt_sa01")
        self.txt_sa01.setGeometry(QRect(110, 110, 61, 61))
        self.txt_sa01.setFont(font1)
        self.txt_sa01.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_sa01.setAlignment(Qt.AlignCenter)
        self.txt_sa11 = QLineEdit(self.tab_suma)
        self.txt_sa11.setObjectName(u"txt_sa11")
        self.txt_sa11.setGeometry(QRect(110, 190, 61, 61))
        self.txt_sa11.setFont(font1)
        self.txt_sa11.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_sa11.setAlignment(Qt.AlignCenter)
        self.txt_sa21 = QLineEdit(self.tab_suma)
        self.txt_sa21.setObjectName(u"txt_sa21")
        self.txt_sa21.setGeometry(QRect(110, 270, 61, 61))
        self.txt_sa21.setFont(font1)
        self.txt_sa21.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_sa21.setAlignment(Qt.AlignCenter)
        self.txt_sa02 = QLineEdit(self.tab_suma)
        self.txt_sa02.setObjectName(u"txt_sa02")
        self.txt_sa02.setGeometry(QRect(190, 110, 61, 61))
        self.txt_sa02.setFont(font1)
        self.txt_sa02.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_sa02.setAlignment(Qt.AlignCenter)
        self.txt_sa12 = QLineEdit(self.tab_suma)
        self.txt_sa12.setObjectName(u"txt_sa12")
        self.txt_sa12.setGeometry(QRect(190, 190, 61, 61))
        self.txt_sa12.setFont(font1)
        self.txt_sa12.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_sa12.setAlignment(Qt.AlignCenter)
        self.txt_sa22 = QLineEdit(self.tab_suma)
        self.txt_sa22.setObjectName(u"txt_sa22")
        self.txt_sa22.setGeometry(QRect(190, 270, 61, 61))
        self.txt_sa22.setFont(font1)
        self.txt_sa22.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_sa22.setAlignment(Qt.AlignCenter)
        self.label_3 = QLabel(self.tab_suma)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(310, 50, 221, 31))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush4)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette2.setBrush(QPalette.Active, QPalette.HighlightedText, brush5)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush5)
        self.label_3.setPalette(palette2)
        self.label_3.setStyleSheet(u"font: 16pt \"SDK_JP_Web\";\n"
"\n"
"")
        self.txt_sb00 = QLineEdit(self.tab_suma)
        self.txt_sb00.setObjectName(u"txt_sb00")
        self.txt_sb00.setGeometry(QRect(310, 110, 61, 61))
        self.txt_sb00.setFont(font1)
        self.txt_sb00.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_sb00.setAlignment(Qt.AlignCenter)
        self.txt_sb01 = QLineEdit(self.tab_suma)
        self.txt_sb01.setObjectName(u"txt_sb01")
        self.txt_sb01.setGeometry(QRect(390, 110, 61, 61))
        self.txt_sb01.setFont(font1)
        self.txt_sb01.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_sb01.setAlignment(Qt.AlignCenter)
        self.txt_sb02 = QLineEdit(self.tab_suma)
        self.txt_sb02.setObjectName(u"txt_sb02")
        self.txt_sb02.setGeometry(QRect(470, 110, 61, 61))
        self.txt_sb02.setFont(font1)
        self.txt_sb02.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_sb02.setAlignment(Qt.AlignCenter)
        self.txt_sb10 = QLineEdit(self.tab_suma)
        self.txt_sb10.setObjectName(u"txt_sb10")
        self.txt_sb10.setGeometry(QRect(310, 190, 61, 61))
        self.txt_sb10.setFont(font1)
        self.txt_sb10.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_sb10.setAlignment(Qt.AlignCenter)
        self.txt_sb11 = QLineEdit(self.tab_suma)
        self.txt_sb11.setObjectName(u"txt_sb11")
        self.txt_sb11.setGeometry(QRect(390, 190, 61, 61))
        self.txt_sb11.setFont(font1)
        self.txt_sb11.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_sb11.setAlignment(Qt.AlignCenter)
        self.txt_sb12 = QLineEdit(self.tab_suma)
        self.txt_sb12.setObjectName(u"txt_sb12")
        self.txt_sb12.setGeometry(QRect(470, 190, 61, 61))
        self.txt_sb12.setFont(font1)
        self.txt_sb12.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_sb12.setAlignment(Qt.AlignCenter)
        self.txt_sb20 = QLineEdit(self.tab_suma)
        self.txt_sb20.setObjectName(u"txt_sb20")
        self.txt_sb20.setGeometry(QRect(310, 270, 61, 61))
        self.txt_sb20.setFont(font1)
        self.txt_sb20.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_sb20.setAlignment(Qt.AlignCenter)
        self.txt_sb21 = QLineEdit(self.tab_suma)
        self.txt_sb21.setObjectName(u"txt_sb21")
        self.txt_sb21.setGeometry(QRect(390, 270, 61, 61))
        self.txt_sb21.setFont(font1)
        self.txt_sb21.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_sb21.setAlignment(Qt.AlignCenter)
        self.txt_sb22 = QLineEdit(self.tab_suma)
        self.txt_sb22.setObjectName(u"txt_sb22")
        self.txt_sb22.setGeometry(QRect(470, 270, 61, 61))
        self.txt_sb22.setFont(font1)
        self.txt_sb22.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_sb22.setAlignment(Qt.AlignCenter)
        self.label_4 = QLabel(self.tab_suma)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(740, 50, 121, 31))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush4)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette3.setBrush(QPalette.Active, QPalette.HighlightedText, brush5)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush5)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush5)
        self.label_4.setPalette(palette3)
        self.label_4.setStyleSheet(u"font: 16pt \"SDK_JP_Web\";\n"
"\n"
"")
        self.bttn_calcularsuma = QPushButton(self.tab_suma)
        self.bttn_calcularsuma.setObjectName(u"bttn_calcularsuma")
        self.bttn_calcularsuma.setGeometry(QRect(550, 200, 121, 41))
        self.bttn_calcularsuma.setFont(font1)
        self.bttn_calcularsuma.setStyleSheet(u"background-color: rgb(117, 110, 44);")
        self.txt_sR00 = QLineEdit(self.tab_suma)
        self.txt_sR00.setObjectName(u"txt_sR00")
        self.txt_sR00.setGeometry(QRect(690, 110, 61, 61))
        self.txt_sR00.setFont(font1)
        self.txt_sR00.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_sR00.setAlignment(Qt.AlignCenter)
        self.txt_sR01 = QLineEdit(self.tab_suma)
        self.txt_sR01.setObjectName(u"txt_sR01")
        self.txt_sR01.setGeometry(QRect(770, 110, 61, 61))
        self.txt_sR01.setFont(font1)
        self.txt_sR01.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_sR01.setAlignment(Qt.AlignCenter)
        self.txt_sR02 = QLineEdit(self.tab_suma)
        self.txt_sR02.setObjectName(u"txt_sR02")
        self.txt_sR02.setGeometry(QRect(850, 110, 61, 61))
        self.txt_sR02.setFont(font1)
        self.txt_sR02.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_sR02.setAlignment(Qt.AlignCenter)
        self.txt_sR10 = QLineEdit(self.tab_suma)
        self.txt_sR10.setObjectName(u"txt_sR10")
        self.txt_sR10.setGeometry(QRect(690, 190, 61, 61))
        self.txt_sR10.setFont(font1)
        self.txt_sR10.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_sR10.setAlignment(Qt.AlignCenter)
        self.txt_sR11 = QLineEdit(self.tab_suma)
        self.txt_sR11.setObjectName(u"txt_sR11")
        self.txt_sR11.setGeometry(QRect(770, 190, 61, 61))
        self.txt_sR11.setFont(font1)
        self.txt_sR11.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_sR11.setAlignment(Qt.AlignCenter)
        self.txt_sR12 = QLineEdit(self.tab_suma)
        self.txt_sR12.setObjectName(u"txt_sR12")
        self.txt_sR12.setGeometry(QRect(850, 190, 61, 61))
        self.txt_sR12.setFont(font1)
        self.txt_sR12.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_sR12.setAlignment(Qt.AlignCenter)
        self.txt_sR20 = QLineEdit(self.tab_suma)
        self.txt_sR20.setObjectName(u"txt_sR20")
        self.txt_sR20.setGeometry(QRect(690, 270, 61, 61))
        self.txt_sR20.setFont(font1)
        self.txt_sR20.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_sR20.setAlignment(Qt.AlignCenter)
        self.txt_sR21 = QLineEdit(self.tab_suma)
        self.txt_sR21.setObjectName(u"txt_sR21")
        self.txt_sR21.setGeometry(QRect(770, 270, 61, 61))
        self.txt_sR21.setFont(font1)
        self.txt_sR21.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_sR21.setAlignment(Qt.AlignCenter)
        self.txt_sR22 = QLineEdit(self.tab_suma)
        self.txt_sR22.setObjectName(u"txt_sR22")
        self.txt_sR22.setGeometry(QRect(850, 270, 61, 61))
        self.txt_sR22.setFont(font1)
        self.txt_sR22.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_sR22.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.tab_suma, "")
        self.tab_resta = QWidget()
        self.tab_resta.setObjectName(u"tab_resta")
        self.label_5 = QLabel(self.tab_resta)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 50, 221, 31))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Button, brush4)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette4.setBrush(QPalette.Active, QPalette.HighlightedText, brush5)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush4)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush4)
        palette4.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush5)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush3)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush5)
        self.label_5.setPalette(palette4)
        self.label_5.setStyleSheet(u"font: 16pt \"SDK_JP_Web\";\n"
"\n"
"")
        self.label_6 = QLabel(self.tab_resta)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(310, 50, 221, 31))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Active, QPalette.Button, brush4)
        palette5.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette5.setBrush(QPalette.Active, QPalette.HighlightedText, brush5)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.Button, brush4)
        palette5.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush4)
        palette5.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush5)
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush3)
        palette5.setBrush(QPalette.Disabled, QPalette.Button, brush4)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette5.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush5)
        self.label_6.setPalette(palette5)
        self.label_6.setStyleSheet(u"font: 16pt \"SDK_JP_Web\";\n"
"\n"
"")
        self.label_7 = QLabel(self.tab_resta)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(740, 50, 121, 31))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Active, QPalette.Button, brush4)
        palette6.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette6.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette6.setBrush(QPalette.Active, QPalette.HighlightedText, brush5)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.Button, brush4)
        palette6.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette6.setBrush(QPalette.Inactive, QPalette.Window, brush4)
        palette6.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush5)
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush3)
        palette6.setBrush(QPalette.Disabled, QPalette.Button, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush5)
        self.label_7.setPalette(palette6)
        self.label_7.setStyleSheet(u"font: 16pt \"SDK_JP_Web\";\n"
"\n"
"")
        self.txt_ra00 = QLineEdit(self.tab_resta)
        self.txt_ra00.setObjectName(u"txt_ra00")
        self.txt_ra00.setGeometry(QRect(30, 110, 61, 61))
        self.txt_ra00.setFont(font1)
        self.txt_ra00.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_ra00.setAlignment(Qt.AlignCenter)
        self.txt_ra01 = QLineEdit(self.tab_resta)
        self.txt_ra01.setObjectName(u"txt_ra01")
        self.txt_ra01.setGeometry(QRect(110, 110, 61, 61))
        self.txt_ra01.setFont(font1)
        self.txt_ra01.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_ra01.setAlignment(Qt.AlignCenter)
        self.txt_ra02 = QLineEdit(self.tab_resta)
        self.txt_ra02.setObjectName(u"txt_ra02")
        self.txt_ra02.setGeometry(QRect(190, 110, 61, 61))
        self.txt_ra02.setFont(font1)
        self.txt_ra02.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_ra02.setAlignment(Qt.AlignCenter)
        self.txt_ra10 = QLineEdit(self.tab_resta)
        self.txt_ra10.setObjectName(u"txt_ra10")
        self.txt_ra10.setGeometry(QRect(30, 190, 61, 61))
        self.txt_ra10.setFont(font1)
        self.txt_ra10.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_ra10.setAlignment(Qt.AlignCenter)
        self.txt_ra11 = QLineEdit(self.tab_resta)
        self.txt_ra11.setObjectName(u"txt_ra11")
        self.txt_ra11.setGeometry(QRect(110, 190, 61, 61))
        self.txt_ra11.setFont(font1)
        self.txt_ra11.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_ra11.setAlignment(Qt.AlignCenter)
        self.txt_ra12 = QLineEdit(self.tab_resta)
        self.txt_ra12.setObjectName(u"txt_ra12")
        self.txt_ra12.setGeometry(QRect(190, 190, 61, 61))
        self.txt_ra12.setFont(font1)
        self.txt_ra12.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_ra12.setAlignment(Qt.AlignCenter)
        self.txt_ra20 = QLineEdit(self.tab_resta)
        self.txt_ra20.setObjectName(u"txt_ra20")
        self.txt_ra20.setGeometry(QRect(30, 270, 61, 61))
        self.txt_ra20.setFont(font1)
        self.txt_ra20.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_ra20.setAlignment(Qt.AlignCenter)
        self.txt_ra21 = QLineEdit(self.tab_resta)
        self.txt_ra21.setObjectName(u"txt_ra21")
        self.txt_ra21.setGeometry(QRect(110, 270, 61, 61))
        self.txt_ra21.setFont(font1)
        self.txt_ra21.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_ra21.setAlignment(Qt.AlignCenter)
        self.txt_ra22 = QLineEdit(self.tab_resta)
        self.txt_ra22.setObjectName(u"txt_ra22")
        self.txt_ra22.setGeometry(QRect(190, 270, 61, 61))
        self.txt_ra22.setFont(font1)
        self.txt_ra22.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_ra22.setAlignment(Qt.AlignCenter)
        self.txt_rb00 = QLineEdit(self.tab_resta)
        self.txt_rb00.setObjectName(u"txt_rb00")
        self.txt_rb00.setGeometry(QRect(310, 110, 61, 61))
        self.txt_rb00.setFont(font1)
        self.txt_rb00.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_rb00.setAlignment(Qt.AlignCenter)
        self.txt_rb01 = QLineEdit(self.tab_resta)
        self.txt_rb01.setObjectName(u"txt_rb01")
        self.txt_rb01.setGeometry(QRect(390, 110, 61, 61))
        self.txt_rb01.setFont(font1)
        self.txt_rb01.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_rb01.setAlignment(Qt.AlignCenter)
        self.txt_rb02 = QLineEdit(self.tab_resta)
        self.txt_rb02.setObjectName(u"txt_rb02")
        self.txt_rb02.setGeometry(QRect(470, 110, 61, 61))
        self.txt_rb02.setFont(font1)
        self.txt_rb02.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_rb02.setAlignment(Qt.AlignCenter)
        self.txt_rb10 = QLineEdit(self.tab_resta)
        self.txt_rb10.setObjectName(u"txt_rb10")
        self.txt_rb10.setGeometry(QRect(310, 190, 61, 61))
        self.txt_rb10.setFont(font1)
        self.txt_rb10.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_rb10.setAlignment(Qt.AlignCenter)
        self.txt_rb11 = QLineEdit(self.tab_resta)
        self.txt_rb11.setObjectName(u"txt_rb11")
        self.txt_rb11.setGeometry(QRect(390, 190, 61, 61))
        self.txt_rb11.setFont(font1)
        self.txt_rb11.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_rb11.setAlignment(Qt.AlignCenter)
        self.txt_rb12 = QLineEdit(self.tab_resta)
        self.txt_rb12.setObjectName(u"txt_rb12")
        self.txt_rb12.setGeometry(QRect(470, 190, 61, 61))
        self.txt_rb12.setFont(font1)
        self.txt_rb12.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_rb12.setAlignment(Qt.AlignCenter)
        self.txt_rb20 = QLineEdit(self.tab_resta)
        self.txt_rb20.setObjectName(u"txt_rb20")
        self.txt_rb20.setGeometry(QRect(310, 270, 61, 61))
        self.txt_rb20.setFont(font1)
        self.txt_rb20.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_rb20.setAlignment(Qt.AlignCenter)
        self.txt_rb21 = QLineEdit(self.tab_resta)
        self.txt_rb21.setObjectName(u"txt_rb21")
        self.txt_rb21.setGeometry(QRect(390, 270, 61, 61))
        self.txt_rb21.setFont(font1)
        self.txt_rb21.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_rb21.setAlignment(Qt.AlignCenter)
        self.txt_rb22 = QLineEdit(self.tab_resta)
        self.txt_rb22.setObjectName(u"txt_rb22")
        self.txt_rb22.setGeometry(QRect(470, 270, 61, 61))
        self.txt_rb22.setFont(font1)
        self.txt_rb22.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_rb22.setAlignment(Qt.AlignCenter)
        self.bttn_calcularresta = QPushButton(self.tab_resta)
        self.bttn_calcularresta.setObjectName(u"bttn_calcularresta")
        self.bttn_calcularresta.setGeometry(QRect(550, 200, 121, 41))
        self.bttn_calcularresta.setFont(font1)
        self.bttn_calcularresta.setStyleSheet(u"background-color: rgb(117, 110, 44);")
        self.txt_rR00 = QLineEdit(self.tab_resta)
        self.txt_rR00.setObjectName(u"txt_rR00")
        self.txt_rR00.setGeometry(QRect(690, 110, 61, 61))
        self.txt_rR00.setFont(font1)
        self.txt_rR00.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_rR00.setAlignment(Qt.AlignCenter)
        self.txt_rR01 = QLineEdit(self.tab_resta)
        self.txt_rR01.setObjectName(u"txt_rR01")
        self.txt_rR01.setGeometry(QRect(770, 110, 61, 61))
        self.txt_rR01.setFont(font1)
        self.txt_rR01.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_rR01.setAlignment(Qt.AlignCenter)
        self.txt_rR02 = QLineEdit(self.tab_resta)
        self.txt_rR02.setObjectName(u"txt_rR02")
        self.txt_rR02.setGeometry(QRect(850, 110, 61, 61))
        self.txt_rR02.setFont(font1)
        self.txt_rR02.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_rR02.setAlignment(Qt.AlignCenter)
        self.txt_rR10 = QLineEdit(self.tab_resta)
        self.txt_rR10.setObjectName(u"txt_rR10")
        self.txt_rR10.setGeometry(QRect(690, 190, 61, 61))
        self.txt_rR10.setFont(font1)
        self.txt_rR10.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_rR10.setAlignment(Qt.AlignCenter)
        self.txt_rR11 = QLineEdit(self.tab_resta)
        self.txt_rR11.setObjectName(u"txt_rR11")
        self.txt_rR11.setGeometry(QRect(770, 190, 61, 61))
        self.txt_rR11.setFont(font1)
        self.txt_rR11.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_rR11.setAlignment(Qt.AlignCenter)
        self.txt_rR12 = QLineEdit(self.tab_resta)
        self.txt_rR12.setObjectName(u"txt_rR12")
        self.txt_rR12.setGeometry(QRect(850, 190, 61, 61))
        self.txt_rR12.setFont(font1)
        self.txt_rR12.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_rR12.setAlignment(Qt.AlignCenter)
        self.txt_rR20 = QLineEdit(self.tab_resta)
        self.txt_rR20.setObjectName(u"txt_rR20")
        self.txt_rR20.setGeometry(QRect(690, 270, 61, 61))
        self.txt_rR20.setFont(font1)
        self.txt_rR20.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_rR20.setAlignment(Qt.AlignCenter)
        self.txt_rR21 = QLineEdit(self.tab_resta)
        self.txt_rR21.setObjectName(u"txt_rR21")
        self.txt_rR21.setGeometry(QRect(770, 270, 61, 61))
        self.txt_rR21.setFont(font1)
        self.txt_rR21.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_rR21.setAlignment(Qt.AlignCenter)
        self.txt_rR22 = QLineEdit(self.tab_resta)
        self.txt_rR22.setObjectName(u"txt_rR22")
        self.txt_rR22.setGeometry(QRect(850, 270, 61, 61))
        self.txt_rR22.setFont(font1)
        self.txt_rR22.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_rR22.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.tab_resta, "")
        self.tab_multiplicacion = QWidget()
        self.tab_multiplicacion.setObjectName(u"tab_multiplicacion")
        self.txt_ma20 = QLineEdit(self.tab_multiplicacion)
        self.txt_ma20.setObjectName(u"txt_ma20")
        self.txt_ma20.setGeometry(QRect(30, 270, 61, 61))
        self.txt_ma20.setFont(font1)
        self.txt_ma20.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_ma20.setAlignment(Qt.AlignCenter)
        self.txt_mb11 = QLineEdit(self.tab_multiplicacion)
        self.txt_mb11.setObjectName(u"txt_mb11")
        self.txt_mb11.setGeometry(QRect(390, 190, 61, 61))
        self.txt_mb11.setFont(font1)
        self.txt_mb11.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_mb11.setAlignment(Qt.AlignCenter)
        self.label_14 = QLabel(self.tab_multiplicacion)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(310, 50, 221, 31))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Active, QPalette.Button, brush4)
        palette7.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette7.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette7.setBrush(QPalette.Active, QPalette.HighlightedText, brush5)
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.Button, brush4)
        palette7.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette7.setBrush(QPalette.Inactive, QPalette.Window, brush4)
        palette7.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush5)
        palette7.setBrush(QPalette.Disabled, QPalette.WindowText, brush3)
        palette7.setBrush(QPalette.Disabled, QPalette.Button, brush4)
        palette7.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette7.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette7.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush5)
        self.label_14.setPalette(palette7)
        self.label_14.setStyleSheet(u"font: 16pt \"SDK_JP_Web\";\n"
"\n"
"")
        self.txt_mb21 = QLineEdit(self.tab_multiplicacion)
        self.txt_mb21.setObjectName(u"txt_mb21")
        self.txt_mb21.setGeometry(QRect(390, 270, 61, 61))
        self.txt_mb21.setFont(font1)
        self.txt_mb21.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_mb21.setAlignment(Qt.AlignCenter)
        self.txt_ma21 = QLineEdit(self.tab_multiplicacion)
        self.txt_ma21.setObjectName(u"txt_ma21")
        self.txt_ma21.setGeometry(QRect(110, 270, 61, 61))
        self.txt_ma21.setFont(font1)
        self.txt_ma21.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_ma21.setAlignment(Qt.AlignCenter)
        self.txt_mb00 = QLineEdit(self.tab_multiplicacion)
        self.txt_mb00.setObjectName(u"txt_mb00")
        self.txt_mb00.setGeometry(QRect(310, 110, 61, 61))
        self.txt_mb00.setFont(font1)
        self.txt_mb00.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_mb00.setAlignment(Qt.AlignCenter)
        self.txt_ma12 = QLineEdit(self.tab_multiplicacion)
        self.txt_ma12.setObjectName(u"txt_ma12")
        self.txt_ma12.setGeometry(QRect(190, 190, 61, 61))
        self.txt_ma12.setFont(font1)
        self.txt_ma12.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_ma12.setAlignment(Qt.AlignCenter)
        self.txt_ma11 = QLineEdit(self.tab_multiplicacion)
        self.txt_ma11.setObjectName(u"txt_ma11")
        self.txt_ma11.setGeometry(QRect(110, 190, 61, 61))
        self.txt_ma11.setFont(font1)
        self.txt_ma11.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_ma11.setAlignment(Qt.AlignCenter)
        self.txt_ma22 = QLineEdit(self.tab_multiplicacion)
        self.txt_ma22.setObjectName(u"txt_ma22")
        self.txt_ma22.setGeometry(QRect(190, 270, 61, 61))
        self.txt_ma22.setFont(font1)
        self.txt_ma22.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_ma22.setAlignment(Qt.AlignCenter)
        self.txt_mb02 = QLineEdit(self.tab_multiplicacion)
        self.txt_mb02.setObjectName(u"txt_mb02")
        self.txt_mb02.setGeometry(QRect(470, 110, 61, 61))
        self.txt_mb02.setFont(font1)
        self.txt_mb02.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_mb02.setAlignment(Qt.AlignCenter)
        self.txt_ma10 = QLineEdit(self.tab_multiplicacion)
        self.txt_ma10.setObjectName(u"txt_ma10")
        self.txt_ma10.setGeometry(QRect(30, 190, 61, 61))
        self.txt_ma10.setFont(font1)
        self.txt_ma10.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_ma10.setAlignment(Qt.AlignCenter)
        self.txt_mR10 = QLineEdit(self.tab_multiplicacion)
        self.txt_mR10.setObjectName(u"txt_mR10")
        self.txt_mR10.setGeometry(QRect(690, 190, 61, 61))
        self.txt_mR10.setFont(font1)
        self.txt_mR10.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_mR10.setAlignment(Qt.AlignCenter)
        self.txt_ma01 = QLineEdit(self.tab_multiplicacion)
        self.txt_ma01.setObjectName(u"txt_ma01")
        self.txt_ma01.setGeometry(QRect(110, 110, 61, 61))
        self.txt_ma01.setFont(font1)
        self.txt_ma01.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_ma01.setAlignment(Qt.AlignCenter)
        self.txt_mR02 = QLineEdit(self.tab_multiplicacion)
        self.txt_mR02.setObjectName(u"txt_mR02")
        self.txt_mR02.setGeometry(QRect(850, 110, 61, 61))
        self.txt_mR02.setFont(font1)
        self.txt_mR02.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_mR02.setAlignment(Qt.AlignCenter)
        self.txt_mR01 = QLineEdit(self.tab_multiplicacion)
        self.txt_mR01.setObjectName(u"txt_mR01")
        self.txt_mR01.setGeometry(QRect(770, 110, 61, 61))
        self.txt_mR01.setFont(font1)
        self.txt_mR01.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_mR01.setAlignment(Qt.AlignCenter)
        self.bttn_calcularmulti = QPushButton(self.tab_multiplicacion)
        self.bttn_calcularmulti.setObjectName(u"bttn_calcularmulti")
        self.bttn_calcularmulti.setGeometry(QRect(550, 200, 121, 41))
        self.bttn_calcularmulti.setFont(font1)
        self.bttn_calcularmulti.setStyleSheet(u"background-color: rgb(117, 110, 44);")
        self.label_15 = QLabel(self.tab_multiplicacion)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(740, 50, 121, 31))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette8.setBrush(QPalette.Active, QPalette.Button, brush4)
        palette8.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette8.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette8.setBrush(QPalette.Active, QPalette.HighlightedText, brush5)
        palette8.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette8.setBrush(QPalette.Inactive, QPalette.Button, brush4)
        palette8.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette8.setBrush(QPalette.Inactive, QPalette.Window, brush4)
        palette8.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush5)
        palette8.setBrush(QPalette.Disabled, QPalette.WindowText, brush3)
        palette8.setBrush(QPalette.Disabled, QPalette.Button, brush4)
        palette8.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette8.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette8.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush5)
        self.label_15.setPalette(palette8)
        self.label_15.setStyleSheet(u"font: 16pt \"SDK_JP_Web\";\n"
"\n"
"")
        self.txt_mR00 = QLineEdit(self.tab_multiplicacion)
        self.txt_mR00.setObjectName(u"txt_mR00")
        self.txt_mR00.setGeometry(QRect(690, 110, 61, 61))
        self.txt_mR00.setFont(font1)
        self.txt_mR00.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_mR00.setAlignment(Qt.AlignCenter)
        self.txt_mR11 = QLineEdit(self.tab_multiplicacion)
        self.txt_mR11.setObjectName(u"txt_mR11")
        self.txt_mR11.setGeometry(QRect(770, 190, 61, 61))
        self.txt_mR11.setFont(font1)
        self.txt_mR11.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_mR11.setAlignment(Qt.AlignCenter)
        self.txt_mb22 = QLineEdit(self.tab_multiplicacion)
        self.txt_mb22.setObjectName(u"txt_mb22")
        self.txt_mb22.setGeometry(QRect(470, 270, 61, 61))
        self.txt_mb22.setFont(font1)
        self.txt_mb22.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_mb22.setAlignment(Qt.AlignCenter)
        self.txt_ma02 = QLineEdit(self.tab_multiplicacion)
        self.txt_ma02.setObjectName(u"txt_ma02")
        self.txt_ma02.setGeometry(QRect(190, 110, 61, 61))
        self.txt_ma02.setFont(font1)
        self.txt_ma02.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_ma02.setAlignment(Qt.AlignCenter)
        self.txt_mb10 = QLineEdit(self.tab_multiplicacion)
        self.txt_mb10.setObjectName(u"txt_mb10")
        self.txt_mb10.setGeometry(QRect(310, 190, 61, 61))
        self.txt_mb10.setFont(font1)
        self.txt_mb10.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_mb10.setAlignment(Qt.AlignCenter)
        self.txt_mb12 = QLineEdit(self.tab_multiplicacion)
        self.txt_mb12.setObjectName(u"txt_mb12")
        self.txt_mb12.setGeometry(QRect(470, 190, 61, 61))
        self.txt_mb12.setFont(font1)
        self.txt_mb12.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_mb12.setAlignment(Qt.AlignCenter)
        self.txt_mR12 = QLineEdit(self.tab_multiplicacion)
        self.txt_mR12.setObjectName(u"txt_mR12")
        self.txt_mR12.setGeometry(QRect(850, 190, 61, 61))
        self.txt_mR12.setFont(font1)
        self.txt_mR12.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_mR12.setAlignment(Qt.AlignCenter)
        self.txt_mR20 = QLineEdit(self.tab_multiplicacion)
        self.txt_mR20.setObjectName(u"txt_mR20")
        self.txt_mR20.setGeometry(QRect(690, 270, 61, 61))
        self.txt_mR20.setFont(font1)
        self.txt_mR20.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_mR20.setAlignment(Qt.AlignCenter)
        self.label_16 = QLabel(self.tab_multiplicacion)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(30, 50, 221, 31))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Active, QPalette.Button, brush4)
        palette9.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette9.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette9.setBrush(QPalette.Active, QPalette.HighlightedText, brush5)
        palette9.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette9.setBrush(QPalette.Inactive, QPalette.Button, brush4)
        palette9.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette9.setBrush(QPalette.Inactive, QPalette.Window, brush4)
        palette9.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush5)
        palette9.setBrush(QPalette.Disabled, QPalette.WindowText, brush3)
        palette9.setBrush(QPalette.Disabled, QPalette.Button, brush4)
        palette9.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette9.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette9.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush5)
        self.label_16.setPalette(palette9)
        self.label_16.setStyleSheet(u"font: 16pt \"SDK_JP_Web\";\n"
"\n"
"")
        self.txt_mR21 = QLineEdit(self.tab_multiplicacion)
        self.txt_mR21.setObjectName(u"txt_mR21")
        self.txt_mR21.setGeometry(QRect(770, 270, 61, 61))
        self.txt_mR21.setFont(font1)
        self.txt_mR21.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_mR21.setAlignment(Qt.AlignCenter)
        self.txt_mR22 = QLineEdit(self.tab_multiplicacion)
        self.txt_mR22.setObjectName(u"txt_mR22")
        self.txt_mR22.setGeometry(QRect(850, 270, 61, 61))
        self.txt_mR22.setFont(font1)
        self.txt_mR22.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_mR22.setAlignment(Qt.AlignCenter)
        self.txt_ma00 = QLineEdit(self.tab_multiplicacion)
        self.txt_ma00.setObjectName(u"txt_ma00")
        self.txt_ma00.setGeometry(QRect(30, 110, 61, 61))
        self.txt_ma00.setFont(font1)
        self.txt_ma00.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_ma00.setAlignment(Qt.AlignCenter)
        self.txt_mb01 = QLineEdit(self.tab_multiplicacion)
        self.txt_mb01.setObjectName(u"txt_mb01")
        self.txt_mb01.setGeometry(QRect(390, 110, 61, 61))
        self.txt_mb01.setFont(font1)
        self.txt_mb01.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_mb01.setAlignment(Qt.AlignCenter)
        self.txt_mb20 = QLineEdit(self.tab_multiplicacion)
        self.txt_mb20.setObjectName(u"txt_mb20")
        self.txt_mb20.setGeometry(QRect(310, 270, 61, 61))
        self.txt_mb20.setFont(font1)
        self.txt_mb20.setStyleSheet(u"background-color: rgb(164, 194, 201);")
        self.txt_mb20.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.tab_multiplicacion, "")
        self.verticalLayoutWidget_3 = QWidget(Dialog)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(300, 19, 361, 41))
        self.verticalLayout_3 = QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.verticalLayoutWidget_3)
        self.label.setObjectName(u"label")
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette10.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette10.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette10.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.WindowText, brush3)
        palette10.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.label.setPalette(palette10)
        self.label.setFont(font)
        self.label.setStyleSheet(u"")

        self.verticalLayout_3.addWidget(self.label)


        self.retranslateUi(Dialog)

        self.tabWidget.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"Ingrese la matriz A:", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"Ingrese la matriz B:", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"Resultado:", None))
        self.bttn_calcularsuma.setText(QCoreApplication.translate("Dialog", u"Calcular", None))
        self.txt_sR00.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_suma), QCoreApplication.translate("Dialog", u"Suma", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"Ingrese la matriz A:", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"Ingrese la matriz B:", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"Resultado:", None))
        self.bttn_calcularresta.setText(QCoreApplication.translate("Dialog", u"Calcular", None))
        self.txt_rR00.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_resta), QCoreApplication.translate("Dialog", u"Resta", None))
        self.label_14.setText(QCoreApplication.translate("Dialog", u"Ingrese la matriz B:", None))
        self.bttn_calcularmulti.setText(QCoreApplication.translate("Dialog", u"Calcular", None))
        self.label_15.setText(QCoreApplication.translate("Dialog", u"Resultado:", None))
        self.txt_mR00.setText("")
        self.label_16.setText(QCoreApplication.translate("Dialog", u"Ingrese la matriz A:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_multiplicacion), QCoreApplication.translate("Dialog", u"Multiplicaci\u00f3n", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"OPERACIONES CON MATRICES", None))
    # retranslateUi

